#!/bin/bash
make -f binom.mak clean
make -f eranduchi.mak clean
make -f erandudots.mak clean
make -f erandugen.mak clean
make -f erandunorm.mak clean
make -f erandupat.mak clean
make -f erandupbm.mak clean
make -f eranduppm.mak clean
make -f eranduraw.mak clean
make -f erandutim.mak clean
make -f mcbell.mak clean
make -f mccos.mak clean
make -f mcparab.mak clean
make -f mcpi.mak clean
make -f mcsin.mak clean
make -f mcsph.mak clean
make -f poischi.mak clean
make -f pwrball.mak clean
make -f ranwlk.mak clean
make -f tsterandu.mak clean
make -f uintchi.mak clean
