#!/bin/bash
make -f binom.mak
make -f eranduchi.mak
make -f erandudots.mak
make -f erandugen.mak
make -f erandunorm.mak
make -f erandupat.mak
make -f erandupbm.mak
make -f eranduraw.mak
make -f erandutim.mak
make -f mcbell.mak
make -f mccos.mak
make -f mcparab.mak
make -f mcpi.mak
make -f mcsin.mak
make -f mcsph.mak
make -f poischi.mak
make -f pwrball.mak
make -f ranwlk.mak
make -f tsterandu.mak
make -f uintchi.mak
